name: "Lesson 3 - Exercise 1"

on:
    workflow_dispatch:

jobs:
    reuse-workflow:
      uses: DaliCariad/post-your-work-project/.github/workflows/lesson3_exercice1.yaml@main
      with:
          actor: ${{ github.actor }}
